### ISSUE TITLE
[Meta] Performance improvements

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#1914]
A meta issue to collect ideas to work on:
- [x] collect metrics on live sites about loading/rendering/etc times https://github.com/yunity/karrot-frontend/pull/1916
  - chrome (but not firefox) will give interesting things on `performance.getEntriesByType("paint")`
  - ... but we also want to define our own version of "First Meaningful Paint" (e.g. a wall post on the screen), also maybe various intermediate steps (e.g. `hasView` on `Root.vue`)
  - other places to consider:
    - when Root.vue is created/rendered?
    - ..?
- [ ] big one: javascript execution time...
- [x] don't serve fullsize images on group preview page https://github.com/yunity/karrot-frontend/commit/db903ccc5445303239f5dcb62ee842ade3cc249a
- [ ] preload webfonts/css/whatever? (somehow get webpack to know what to do load...)
  - [x] webfonts yunity/karrot-frontend#1915
- [x] `Object.freeze` stuff we don't need reactive (e.g. each individual pickup, in the mutation), to reduce time spent in `_traverse` function #1945
- [ ] use better image formats, google says: _JPEG 2000, JPEG XR, and WebP often provide better compression than PNG or JPEG_
- [ ] investigate loading core js libraries in a main (preloaded?) entry rather than a common chunk (e.g. vuex, quasar...)
- [ ] reduce amount of "all group" data loaded always (group infos, places, ... maybe users?) - this is maybe not so much performance related though
- [ ] optimize loading time of one page, e.g. group wall: reduce number of backend requests, javascript files etc...

**Comment by tiltec** [comment]
Feedback from Bruno, things that feel slow:
- opening notifications takes some time, delayed loading feels "slow"
- in app, "trying to connect to server" can constantly appear and makes it feels slow

**Comment by tiltec** [comment]
I noticed most of the chunks in Karrot change between deploys, even when there are not many changes. It seems due to scoped css id - they get calculated by hashing the whole SFC source file (not just the style section). The parent component apparently needs to know about the scope id. If component x is used 10 times and x changes, this will invalidate about 11 chunks.
Maybe not super important to fix, but still quite unexpected.

**Comment by tiltec** [comment]
I tried out more aggressive chunking in https://github.com/yunity/karrot-frontend/commit/0bbae6fd9e6d0b5317d79ad2edce5c338b6c91aa. It seems to cause slight slowdown on dev.karrot.world and local testing, so I'll roll it back.

**Comment by tiltec** [comment]
We could try less aggressive splitting, i.e. increase `splitChunks.minSize` - that would increase download size and worsen caching efficiency, but maybe slightly improve parsing speed due to hoisting?

**Comment by nicksellen** [comment]
https://web.dev/vitals/ is an approach with an associated js lib that is able to collect some of the types of stuff added in https://github.com/yunity/karrot-frontend/pull/1916, but browser support is not good https://github.com/GoogleChrome/web-vitals#browser-support (basically only chromium).

**Comment by tiltec** [comment]
We just looked at recent numbers and noticed that our reporting is nice, but it would nice to have better ones.

**Comment by tiltec** [comment]
..but we think loading for logged-in users actually _did_ improve!

**Comment by tiltec** [comment]
Maybe it's useful to have https://github.com/jazzband/django-silk in production as well, to find out which database requests are particularly slow.

**Comment by nicksellen** [comment]
I think performance is OK now, esp. after some of the improvements in https://github.com/karrot-dev/karrot-frontend/issues/2667

... also many of the things in this issue are outdated, now we using different build tool (vite), so I'll this, but make a new issue if it becomes an issue again!
