### ISSUE TITLE
Upgrade to Quasar v2 / Vue v3

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2350]
Quasar v2 (which uses Vue v3) is out in beta now, and it sounds stable enough to start working on our upgrade.

Vue v3 introduces the composition API, but I guess at first we should try and upgrade with as minimal changes as possible.

## TODO

- [ ] upgrade dependency versions
- [ ] go through the upgrade guide https://next.quasar.dev/start/upgrade-guide
- [ ] list outstanding issues (add checkbox for each one)
- [ ] check extensions for Quasar/Vue incompatibility (add checkbox for each)

**Comment by pogopaule** [comment]
I'll give this a shot.

**Comment by pogopaule** [comment]
@nicksellen Quasar moves from Stylus to SASS. It seems we could keep Stylus for our components. Do you think it makes sense to kick out Stylus entirely and replace it with SASS project-wide? Or should we only move to SASS where necessary? https://next.quasar.dev/start/upgrade-guide#option-1-convert-a-project

**Comment by nicksellen** [comment]
Personally, I'd be happy to move to sass. The tooling around it is likely better and simpler to keep aligned with Quasar. What do you think?

The other consideration for now, is if that makes the migration work grow a lot. Would be fine to upgrading keeping with stylus, and consider the switch to sass separately.

**Comment by larzon83** [comment]
+1 for sass.
When keeping stylus and need to use color vars inside a component (`style lang="stylus"`) the vars are now in sass and can't be imported.
Maybe we can have a temp `styl` file that has the same definitions as the new sass file. If one want to define a new var or editing an existing one, changes need to be also done in the styl file. We only have a few vars currently so I think that would be ok.
We also don't need to change linting when keeping stylus.

**Comment by pogopaule** [comment]
Reading [the info box](https://v3.vuejs.org/guide/migration/introduction.html#breaking-changes) I am hesitant to start migrating Vue 2 to Vue 3. @nicksellen and @larzon83 what are your opinions?

I could not find any information if Quasar 2 is compatible with Vue 2. So in case you agree to wait with the migration of Vue, what about the migration of Quasar?

**Comment by larzon83** [comment]
@pogopaule Isn't the point of Quasar v2 to use Vue 3? So, after installing Quasar v2, Vue 3 gets installed?
Anyway, the Vue migration/compat build is currently in beta: https://news.vuejs.org/issues/193

**Comment by tiltec** [comment]
Quasar v2 is now officially released, I had to pin some dependencies in https://github.com/yunity/karrot-frontend/commit/6d826812e9328adebd6b14766695468b3a69b319 to keep the automatic dependency update PRs working. Seems it's finally time to move to Vue3/Quasar2!

@pogopaule Do you think it makes sense to rebase this PR or should we rather follow the migration guide again?

**Comment by tiltec** [comment]
In the last days, I spent some hours progressing the Quasar upgrade - it's quite complex!

Currently, I'm a bit unsure about style files. Quasar doesn't provide ´stylus` variables anymore, so it makes sense to move away from it. I followed @pogopaule's previous approach and converted everything to `sass`, but ran into some linter bugs. It seems that [the sass syntax support](https://github.com/AleshaOleg/postcss-sass) is barely maintained, and [some other issue comment](https://github.com/stylelint/stylelint/issues/4865#issuecomment-847008927) mentions that `scss` is much better supported.

I now tend to convert to `scss`, which is quite similar to plain css with a lot of braces and semicolons. Not as pleasant to write, but probably fine...

**Comment by tiltec** [comment]
`vue-croppa` seems unsupported: https://github.com/zhanziyang/vue-croppa/issues/235

I'm also a bit confused how to use the [vue migration build](https://v3.vuejs.org/guide/migration/migration-build.html). I can set it to run in Vue2 mode by default, and then switch to Vue3 mode on a per-component basis when we are done upgrading. But how about dependencies? Each of them would need to set all their components to Vue3 mode, with weird errors happening otherwise. [Here's an example from vue-leaflet](https://github.com/vue-leaflet/vue-leaflet/pull/147), the successor of vue2-leaflet.

**Comment by nicksellen** [comment]
How does nesting working? E.g. if you made a component with a local config to use vue3 compat mode, do nested components also use vue3? Could be a way? (Either one that sets vue3 mode and renders the child elements, or a small component that directly includes the library one). Maybe doesn't work, but an idea!

**Comment by tiltec** [comment]
I think compat config isn't inherited when nesting components; maybe all vue3-aware dependencies really need to declare vue3 compat mode to make app-wide vue2 mode work.

**Comment by tiltec** [comment]
I found a way to use Croppa with the vue migration build :)

https://github.com/yunity/karrot-frontend/pull/2438/files#diff-ab23cc641c1e9694e36317572cd5dad6aa49f79827fea3fcd77ef466565a13baR89-R91
